version: "3.8"

services:
  api:
    build: ./api
    environment:
      - CONNECTION_STRING=postgres://deso_user:deso_user@db/deso_db
    depends_on:
      - db
    networks:
      - backend
      - frontend

  frontend:
    build: ./frontend
    environment:
      - API_URL=http://api:3001/data
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - frontend

  db:
    image: r.deso.tech/dockerhub/library/postgres:11.2-alpine
    environment:
      POSTGRES_USER: deso_user
      POSTGRES_PASSWORD: deso_user
      POSTGRES_DB: deso_db
    volumes:
      - ./db/init_sql_scripts/:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
  frontend:
